version: '3.4'

services:
  redis:
    image: redis
    container_name: my_redis
    ports:
      - 6379:6379
    networks:
      - lockmanager-network

  lockmanager:
    image: jaepyo99/lockmanager
    container_name: ime_lockmanager
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - lockmanager-network
networks:
  lockmanager-network:
    external: true