version: '3.4'

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    extra_hosts:
      - host.docker.internal:host-geteway
    networks:
      - lockmanager-network

  lockmanager:
    image: jaepyo99/lockermanager
    container_name: ime_lockmanager
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    networks:
      - lockmanager-network
    external_links:
      - redis
networks:
  lockmanager-network:
    driver: bridge