version: '3.4'

services:
  redis:
    image: redis
    container_name: my_redis
    ports:
      - "6379:6379"
    networks:
      - lockermanager-network

  lockmanager:
    image: jaepyo99/lockermanager
    container_name: ime_lockmanager
    ports:
      - "8080:8080"
    networks:
      - lockermanager-network
    depends_on:
      - redis

networks:
  lockmanager-network:
    external: true